@echo off
echo 🔄 Deteniendo procesos de Node.js existentes...
taskkill /f /im node.exe >nul 2>&1
echo ⏱️ Esperando 2 segundos...
timeout /t 2 >nul
echo 🚀 Iniciando servidor...
cd /d "%~dp0"
npm start
